before_install:
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com EC4926EA
  - echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/havana main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libvirt-bin libvirt-dev
language: python
python:
  - "2.7"

# libvirt-python==1.2.2 pip package fails to compile on Ubuntu 12.04 with
# libvirt-dev 1.1.1. As a workaround, I'm installing python-libvirt from APT
# and excluding it from requirements.txt
install:
  - "pip install -r requirements.txt"
  - "pip install -r test/requirements.txt"

script: "nosetests --with-coverage --cover-package=handlers --cover-package=utils"

